### ISSUE TITLE
您方便给下.tour文件吗？

### ISSUE THREAD

**Issue by hu-qi** [binggg/tcb-hackernews#1]
看您的演示项目有写开发指导，但是我暂时没找到对应的.tour，不知道您那边方便添加一下吗？感谢！
![image](https://user-images.githubusercontent.com/17986122/87520858-211b3480-c6b6-11ea-8ce3-abaec5f7e696.png)

**Comment by binggg** [comment]
已经把 .tour 文件提交上去了
